### ISSUE TITLE
Updates on project status

### ISSUE THREAD

**Issue by zakuru** [module-federation/medusa#11]
Hi @ScriptedAlchemy 
First all my respect to you and the work done around webpack and module federation
I was looking into medusa and found it also very useful
But there is no more activity since a while - Do you still recommend to use it or need any help to improve it ?
Thanks

**Comment by ScriptedAlchemy** [comment]
Hey. I have Medusa on a private repo and hired a team to work on it. Keep an eye on my twitter as we are close to publishing an official release for it. 
It'll be SaaS but there free tiers. 
Since I've funded it - we are able to secure it and make it reliable plus have a large roadmap. 
I'll probably reset this public repo to point to the domains and other areas and nice it's ready. 
August 1 is the go live date. DM me on twitter if you want to keep in touch on early access.
